trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'emotion-detection-app'
  ACR_NAME: 'emotiondetectionacr'
  ACR_LOGIN_SERVER: 'emotiondetectionacr.azurecr.io'

steps:
- task: UsePythonVersion@1
  inputs:
    versionSpec: '3.x'

- script: |
    pip install -r app/requirements.txt
    python -m unittest discover app/tests
  displayName: 'Run Unit Tests'

- script: |
    docker build -t $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(Build.BuildId) .
    docker push $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(Build.BuildId)
  displayName: 'Build and Push Docker Image'

- task: AzureWebAppContainer@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: '<your-service-connection>'
    appName: 'emotion-detection-app'
    containers: |
      $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(Build.BuildId)
