name: Docker Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install pytest

      # Step 4: Set PYTHONPATH and run tests
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest app/tests

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test  # Ensures tests pass before building Docker image

    steps:
      # Step 5: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 6: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/emotion-detection-app:latest

  deploy-azure:
    runs-on: ubuntu-latest
    needs: docker-build-push  # Ensures Docker image is built and pushed before deployment

    steps:
      # Step 8: Authenticate with Azure
      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 9: Deploy to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: emotion-detection-app  # Replace with your Azure App Service name
          slot-name: production
          images: ${{ secrets.DOCKER_USERNAME }}/emotion-detection-app:latest
